Post-lecture corrections to VirtualBox demo and minor corrections in style guide
Simulation-Software-Engineering/Lecture-Material pull request #135
Opened 2022-11-10 13:19 UTC by IshaanDesai

## Description

Title is self-explanatory.

## Checklist

- [ ] I made sure that the markdown files are formatted properly.
- [ ] I made sure that all hyperlinks are working.

- [ ] I added the new content to the `README.md` inside the topics subdirectory, e.g., `01_version_control/README.md`.
- [ ] I added the new content to the `timetable.md` in the root of this repository.

2022-11-15 07:40 UTC, uekerman requested changes
We do use "Title Case for Headings", so we should also stick to this in the style guide, no?

2022-11-15 16:58 UTC, IshaanDesai commented
> We do use "Title Case for Headings", so we should also stick to this in the style guide, no?

Okay alright. I will revert all the changes in the headings.

2022-11-16 14:10 UTC, uekerman approved these changes

2022-11-16 14:10 UTC, uekerman commented on docs/styleguide.md
> +### Items that are not full Sentences
```suggestion
### Items That are not Full Sentences
```

2022-11-16 14:16 UTC, merged